### ISSUE TITLE
Ticks seem to work in reverse?

### ISSUE THREAD

**Issue by gee-ell** [hjgwmvya/redirect-control#4]
Just tried this, but the option ticks seem to be reversed? :
- when "Allow request triggered by a link click" is TICKED, I get a warning every time I follow a link (eg. via Google).
- when UNTICKED, the click warnings go away.

**Comment by gee-ell** [comment]
.. correction, the warnings seem to be caused by "Ignore Subdomains".  But again it seems reversed, they only go away when this is unticked?

**Comment by hjgwmvya** [comment]
Thx for your response.

This behavior is intended. In your case you should always get a redirect warning (except there is a specific rule). When you click on a google search result, you get redirected to another google url before you get a second redirect to the clicked link. Because of that the redirect to the link is not triggered by the link click.

You can see this if you uncheck all options and click a google search result. You should get 2 redirect requests.

If you allow a request, the request get allowed for some seconds. Because of that you get not asked again if you do the same request again in a short time.

I hope, I could help you a little bit.
